FIXATION_FILENAME : ['./clean_data_trial.csv']
TRAINING_FRACTION : [.9]
K_FOLDS : [2]
CLASSIFICATION_TYPE : ['inst_v_ninst']
IMAGE_DIR : ['./images']
ALGORITHM_TYPE : ['mfpa-cnn(L)']
PATCH_LENGTH : [9]
BATCH_SIZE : [60]
NETWORK_NAME : ['resnet50']
POOLING_TYPE : ['avg']
LAYER_IDX : [2]
N_KERNELS : [1]
COVARIANCE_TYPE : ['diag']
REG_COVAR : [1e-5]
N_COMPONENTS_FOR_PCA : [256]
KERNEL_TYPE : ['rbf']
C : [1]
LEARNING_RATE : [0.01]
